services:
  fastapi:
    build: ./fastapi
    container_name: fastapi-benchmark
    ports:
      - "8000:8000"

  litestar:
    build: ./litestar
    container_name: litestar-benchmark
    ports:
      - "8000:8000"

  aiohttp:
    build: ./aiohttp
    container_name: aiohttp-benchmark
    ports:
      - "8000:8000"

  tornado:
    build: ./tornado
    container_name: tornado-benchmark
    ports:
      - "8000:8000"

  sanic:
    build: ./sanic
    container_name: sanic-benchmark
    ports:
      - "8000:8000"


